### PR TITLE
Fix possible bad contrast for class list

### PR DESCRIPTION
**Pull request by axtloss**
Fixes the bad contrast between the class background and the text color depending on what the user set as a background color. The text color gets automatically chosen between black and white depending on the users preference.

Screenshot from 2023-06-07 18-19-18

### CODE REVIEW

**Comment by Narzgul** [comment]
Very nice!
Could you maybe add some comments to the _getBestTextColor() Function? It isn't clear why these calculations are done.
Other than that, thank you very much for this contribution!

**Comment by axtloss** [comment]
I added some comments that approximately explain the calculation.

Also a thing to note is that the value it gets compared to in the if-clause (currently 0.6) may have to be adjusted a bit, it gave the best results for the colors that I tested, but there could be some values that yield better results for more colors.

**Comment by Narzgul** [comment]
I don't know if this is my fault, but I can see the commit in your fork of the project, but not in this pull request. Do you know why this is the case or, how I can fix it?

**Comment by axtloss** [comment]
I don't actually know why that happens, I can see them fine on my side.
Maybe it's just github being github?

**Comment by Narzgul** [comment]
Oh yes, now I can see it!
Thank you!

**Pull request merged**
